# Generated by Django 6.0 on 2026-01-04 07:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('payment_method_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_name', models.CharField(max_length=50)),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payment_methods',
                'indexes': [models.Index(fields=['method_name'], name='payment_met_method__237f46_idx'), models.Index(fields=['provider'], name='payment_met_provide_3b2f83_idx')],
                'unique_together': {('method_name', 'provider')},
            },
        ),
    ]
