# Generated by Django 6.0 on 2026-01-04 09:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_vendor'),
        ('finance', '0002_paymentmethod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_refund', models.BooleanField(default=False)),
                ('is_business', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_interval', models.CharField(blank=True, max_length=20, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reconciled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='categories.category')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.paymentmethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='categories.vendor')),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-expense_date'],
                'indexes': [models.Index(fields=['user', 'expense_date'], name='expenses_user_id_56cf09_idx'), models.Index(fields=['account'], name='expenses_account_06ae57_idx'), models.Index(fields=['vendor'], name='expenses_vendor__56d91c_idx'), models.Index(fields=['category'], name='expenses_categor_80dcb8_idx'), models.Index(fields=['is_business'], name='expenses_is_busi_9310bf_idx'), models.Index(fields=['is_recurring'], name='expenses_is_recu_7c3a89_idx')],
            },
        ),
    ]
