# Generated by Django 6.0 on 2026-01-04 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_currency_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('github', 'GitHub'), ('facebook', 'Facebook')], max_length=30)),
                ('provider_uid', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['provider'], name='accounts_so_provide_545279_idx'), models.Index(fields=['email'], name='accounts_so_email_61c860_idx')],
                'unique_together': {('provider', 'provider_uid')},
            },
        ),
    ]
