# Generated by Django 6.0 on 2026-01-04 08:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('transfer', 'Transfer')], max_length=20)),
                ('category_detail_type', models.CharField(blank=True, choices=[('essential', 'Essential'), ('discretionary', 'Discretionary')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'categories',
                'indexes': [models.Index(fields=['category_type'], name='categories_categor_304e6b_idx'), models.Index(fields=['category_detail_type'], name='categories_categor_d58b70_idx')],
                'unique_together': {('category_name', 'category_type')},
            },
        ),
    ]
