# Generated by Django 6.0 on 2026-01-04 08:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_vendors', to='categories.category')),
            ],
            options={
                'db_table': 'vendors',
                'indexes': [models.Index(fields=['vendor_name'], name='vendors_vendor__4ce451_idx'), models.Index(fields=['vendor_type'], name='vendors_vendor__7b13ca_idx'), models.Index(fields=['default_category'], name='vendors_default_17012b_idx')],
                'unique_together': {('vendor_name', 'vendor_type')},
            },
        ),
    ]
