# Generated by Django 6.0 on 2026-01-25 09:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_category_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendor',
            unique_together={('user', 'vendor_name', 'vendor_type')},
        ),
    ]
