# Generated by Django 6.0 on 2026-01-25 10:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_vendor_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendor',
            unique_together={('user', 'vendor_name', 'vendor_type', 'default_category')},
        ),
    ]
